In [1]:
import numpy as np
from scipy import linalg
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
n = 6
A = np.random.randn(n,n)

for k in range(0,n-1):
    for i in range(k+1,n):
        # Calculeaza multiplicatorii Gaussieni
        A[i][k] = -A[i][k]/A[k][k]   # Se suprascriu in triunghiul inferior
        # Aplica multiplicatorii
        for j in range(k+1,n):
            A[i][j] = A[i][j] + A[k][j]*A[i][k]

In [3]:
A_gauss = np.triu(A)
print(A_gauss)

[[-1.01830942 -0.21720869 -0.32028484  0.78248093 -0.19890411  0.85516891]
 [ 0.          0.45017778 -0.46836847  1.38464015 -0.27216334  0.1875674 ]
 [ 0.          0.         -3.05410527 -0.39865709 -0.93684222 -0.42180086]
 [ 0.          0.          0.          0.6553137   0.45383387  1.71934278]
 [ 0.          0.          0.          0.         -2.0576146  -6.27906723]
 [ 0.          0.          0.          0.          0.          4.96257011]]


In [4]:
def prod(A,b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i] = (b[i] - np.dot(A[i][i+1:],x[i+1:]))/A[i][i]
    return x

b = np.random.randn(n)
x = prod(A_gauss,b)
print(x)

[-1.44664813 -1.71363402 -0.28126658  0.08180519  1.23119381 -0.2335044 ]


In [9]:
A = [[2,4,-2], [4, 9, -3],[-2, -3, 7]]
b = [2,8,10]
A = np.array(A)
n = 3
for k in range(0,n-1):
    for i in range(k+1,n):
        # Calculeaza multiplicatorii Gaussieni
        A[i][k] = -A[i][k]/A[k][k]   # Se suprascriu in triunghiul inferior
        # Aplica multiplicatorii
        for j in range(k+1,n):
            A[i][j] = A[i][j] + A[k][j]*A[i][k]

b = np.array(b)  
for k in range(0,n-1):
    for i in range(k+1,n):
        b[i] = b[i] + A[i][k]*b[k]


A = np.triu(A)
print(A)
print(b)

[[ 2  4 -2]
 [ 0  1  1]
 [ 0  0  4]]
[2 4 8]


In [10]:
x = prod(A,b)
print(x)

[-1.  2.  2.]
